import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { Header } from "@/components/layout/header";
import { Sidebar } from "@/components/layout/sidebar/sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DashboardLayout>
      <Header className="col-span-full border-b" />
      <Sidebar className="hidden lg:block col-start-1 border-r" />
      {children}
    </DashboardLayout>
  );
}
